[package]
name = "frond"
version = "0.1.0"
authors = ["Klim Kostiuk <2601074@gmail.com>"]
license = "MIT"
edition = "2024"
readme = "README.md"

[dependencies]
ratatui = { version = "0.29.0", features = ["all-widgets"] }
frond-core = { path = "../frond-core" }
color-eyre = "0.6.5"
uuid = "1.17.0"
chrono = "0.4.0"
